modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="eidolon" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Eidolon" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
# logoFile="examplemod.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="elucent" #optional
description='''
A spooky magic mod about necromancy.
'''
[[dependencies.eidolon]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.3,)"
    ordering="AFTER"
    side="BOTH"